package it.fabiofenoglio.lelohub.domain.enumeration;

/**
 * The SequenceVariable enumeration.
 */
public enum SequenceVariable {
    USER_VARIABLE, MOTOR_SPEED, VIBE_SPEED, CENTRAL_BUTTON_PRESSED, PLUS_BUTTON_PRESSED, MINUS_BUTTON_PRESSED, TEMPERATURE, PRESSURE, INSERTION_DEPTH, ACCELERATION_X, ACCELERATION_Y, ACCELERATION_Z, RUN_TIME, RANDOM
}
