export const enum SequenceVariable {
  USER_VARIABLE = 'USER_VARIABLE',
  MOTOR_SPEED = 'MOTOR_SPEED',
  VIBE_SPEED = 'VIBE_SPEED',
  CENTRAL_BUTTON_PRESSED = 'CENTRAL_BUTTON_PRESSED',
  PLUS_BUTTON_PRESSED = 'PLUS_BUTTON_PRESSED',
  MINUS_BUTTON_PRESSED = 'MINUS_BUTTON_PRESSED',
  TEMPERATURE = 'TEMPERATURE',
  PRESSURE = 'PRESSURE',
  INSERTION_DEPTH = 'INSERTION_DEPTH',
  ACCELERATION_X = 'ACCELERATION_X',
  ACCELERATION_Y = 'ACCELERATION_Y',
  ACCELERATION_Z = 'ACCELERATION_Z',
  RUN_TIME = 'RUN_TIME',
  RANDOM = 'RANDOM'
}
