# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI-CD staging environment

on:
  push:
    branches: [ develoment ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check out private mirror repository
      uses: actions/checkout@master
      with:
        repository: fabiofenoglio/lelo-f1-hub-private
        token: ${{ secrets.pat_private_mirror }}
        path: private_mirror
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Cache node_modules
      uses: actions/cache@v1
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node_modules
    - name: Merge content of private repository
      run: rsync --archive ./private_mirror/ ./
    - name: Build and deploy with Maven
      run: mvn -Pstaging -Dmaven.test.skip=true -DskipTests clean package tomcat7:redeploy --file pom.xml
